name: Podman Run

on:
  workflow_dispatch:

jobs:
  test:
    name: First GitHub Workflow Execution
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello from GitHub Actions!"

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la
      
      - name: Check runner resources
        run: |
          echo "===== OS ====="
          uname -a

          echo "===== CPU ====="
          echo "CPU cores: $(nproc)"
          lscpu | grep -E 'Model name|CPU\(s\)'

          echo "===== RAM ====="
          free -h

          echo "===== DISK ====="
          df -h

          echo "===== RUNNER ====="
          echo "OS: $RUNNER_OS"
          echo "Architecture: $RUNNER_ARCH"