name: Podman Build and Push

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: podman

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Show Repository Files
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f
        
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Verify Podman
        run: |
          podman --version

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          podman login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Build Image
        run: |
          IMAGE_TAG=${{ github.run_number }}

          podman build \
            -f go.Dockerfile
            -t ghcr.io/${{ github.repository_owner }}/golang/${{ env.IMAGE_NAME }}:${IMAGE_TAG} \
            -t ghcr.io/${{ github.repository_owner }}/golang/${{ env.IMAGE_NAME }}:latest \
            .

      - name: Push Version Tag
        run: |
          IMAGE_TAG=${{ github.run_number }}

          podman push \
            ghcr.io/${{ github.repository_owner }}/golang/${{ env.IMAGE_NAME }}:${IMAGE_TAG}

      - name: Push Latest Tag
        run: |
          podman push \
            ghcr.io/${{ github.repository_owner }}/golang/${{ env.IMAGE_NAME }}:latest